### PR TITLE
Fix monad fail

### LINKED ISSUE #2: ‘fail’ is not a (visible) method of class ‘Monad’
From latest commit, ghc ` 8.8.3`, base `4.13.0.0`:
```shell
transformers-abort               > /run/user/1001/stack-62dbeefc3899fae0/transformers-abort-0.6.0.1/src/Control/Monad/Trans/Abort.hs:113:3: error:
transformers-abort               >     ‘fail’ is not a (visible) method of class ‘Monad’
transformers-abort               >     |              
transformers-abort               > 113 |   fail    = AbortT . fail
transformers-abort               >     |   ^^^^       
transformers-abort               >                    
```

### PR DESCRIPTION
**Pull request by Pitometsu**
Fixes #2

### CODE REVIEW

File: src/Control/Monad/Trans/Abort.hs [hunk 1]
```diff
@@ -110,9 +110,10 @@ instance (Functor μ, Monad μ) ⇒ Bind (AbortT e μ) where
 instance Monad μ ⇒ Monad (AbortT e μ) where
   return  = AbortT . return . Right
   m >>= f = AbortT $ runAbortT m >>= either (return . Left) (runAbortT . f)
+#if !MIN_VERSION_base(4,9,0)
```
Comment (mvv) [inline src/Control/Monad/Trans/Abort.hs]: Should be
```haskell
#if !MIN_VERSION_base(4,13,0)
  fail = AbortT . fail
#endif
#if MIN_VERSION_base(4,9,0)
instance Fail.MonadFail ...
#endif
```
otherwise `fail` will default to `error` with base >= 4.9 && <= 4.12

**Review by mvv — CHANGES_REQUESTED** [review]

File: src/Control/Monad/Trans/Abort.hs (hunk 1 above)
Comment (Pitometsu) [reply src/Control/Monad/Trans/Abort.hs]: Thank you, updated.

**Comment by mvv** [comment]
Thanks
